#!/bin/sh
ADDR=inet:localhost:7788
./server -ORBIIOPAddr $ADDR $@ > ref &
server_pid=$!
TM=$(( ( RANDOM % 10 ) + 5 ))
echo "Sleeping for $TM seconds."
sleep $TM
echo "Killing the server: $server_pid"
kill $server_pid
wait
echo "...server died."
